In [1]:
import pandas as pd
import json
import os

from Constants import *

In [2]:
df = pd.read_csv(PATH_TO_ACC_DATA, sep=',')

c:\soft\python36\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df = df[df["DATE"].apply(lambda x: int(x[6:])) >= 2017]

In [63]:
df.columns

Index(['DATE', 'TIME', 'BOROUGH', 'ZIP CODE', 'LATITUDE', 'LONGITUDE',
       'LOCATION', 'ON STREET NAME', 'CROSS STREET NAME', 'OFF STREET NAME',
       'NUMBER OF PERSONS INJURED', 'NUMBER OF PERSONS KILLED',
       'NUMBER OF PEDESTRIANS INJURED', 'NUMBER OF PEDESTRIANS KILLED',
       'NUMBER OF CYCLIST INJURED', 'NUMBER OF CYCLIST KILLED',
       'NUMBER OF MOTORIST INJURED', 'NUMBER OF MOTORIST KILLED',
       'CONTRIBUTING FACTOR VEHICLE 1', 'CONTRIBUTING FACTOR VEHICLE 2',
       'CONTRIBUTING FACTOR VEHICLE 3', 'CONTRIBUTING FACTOR VEHICLE 4',
       'CONTRIBUTING FACTOR VEHICLE 5', 'UNIQUE KEY', 'VEHICLE TYPE CODE 1',
       'VEHICLE TYPE CODE 2', 'VEHICLE TYPE CODE 3', 'VEHICLE TYPE CODE 4',
       'VEHICLE TYPE CODE 5', 'YEAR', 'DAY', 'MONTH'],
      dtype='object')

In [4]:
df

,DATE,TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,UNIQUE KEY,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,10/16/2018,0:00,BROOKLYN,11215,40.668990,-73.996410,"(40.66899, -73.99641)",15 STREET,2 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4001454,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
1,10/16/2018,0:00,MANHATTAN,10039,40.824196,-73.942240,"(40.824196, -73.94224)",NaN,NaN,85 BRADHURST AVENUE,...,NaN,NaN,NaN,NaN,4000711,Sedan,NaN,NaN,NaN,NaN
2,10/16/2018,0:00,QUEENS,11414,40.668860,-73.854910,"(40.66886, -73.85491)",80 STREET,149 AVENUE,NaN,...,NaN,NaN,NaN,NaN,4002838,NaN,NaN,NaN,NaN,NaN
3,10/16/2018,0:00,NaN,NaN,40.788692,-73.937870,"(40.788692, -73.93787)",EAST 106 STREET,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4001629,Sedan,Sedan,NaN,NaN,NaN
4,10/16/2018,0:00,NaN,NaN,40.757668,-73.959150,"(40.757668, -73.95915)",FDR DRIVE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4000768,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
5,10/16/2018,0:00,NaN,NaN,NaN,NaN,NaN,G.C.P. / JEWEL (CDR),NaN,NaN,...,Unspecified,NaN,NaN,NaN,4001417,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
6,10/16/2018,0:00,BRONX,10459,40.818893,-73.892290,"(40.818893, -73.89229)",BRUCKNER BOULEVARD,BARRETTO STREET,NaN,...,Unspecified,NaN,NaN,NaN,4000945,Sedan,Sedan,NaN,NaN,NaN
7,10/16/2018,0:00,STATEN ISLAND,10305,40.594150,-74.086586,"(40.59415, -74.086586)",HYLAN BOULEVARD,REID AVENUE,NaN,...,Unspecified,Unspecified,NaN,NaN,4001356,Sedan,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN
8,10/16/2018,0:05,NaN,NaN,40.743156,-73.972130,"(40.743156, -73.97213)",EAST 34 STREET,FDR DRIVE,NaN,...,Failure to Keep Right,NaN,NaN,NaN,4000756,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
9,10/16/2018,0:10,MANHATTAN,10004,40.706657,-74.015915,"(40.706657, -74.015915)",WEST STREET,MORRIS STREET,NaN,...,Unspecified,NaN,NaN,NaN,4001613,Sedan,Sedan,NaN,NaN,NaN
10,10/16/2018,0:15,NaN,NaN,40.806553,-73.924750,"(40.806553, -73.92475)",EAST 134 STREET,WILLIS AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4000782,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
11,10/16/2018,0:20,MANHATTAN,10013,40.719395,-74.001890,"(40.719395, -74.00189)",CANAL STREET,BROADWAY,NaN,...,Unspecified,NaN,NaN,NaN,4000958,Pick-up Truck,Taxi,NaN,NaN,NaN
12,10/16/2018,0:20,NaN,NaN,40.804226,-73.913010,"(40.804226, -73.91301)",BRUCKNER EXPRESSWAY,NaN,NaN,...,NaN,NaN,NaN,NaN,4000772,Taxi,NaN,NaN,NaN,NaN
13,10/16/2018,0:20,NaN,NaN,40.804226,-73.913010,"(40.804226, -73.91301)",BRUCKNER EXPRESSWAY,NaN,NaN,...,NaN,NaN,NaN,NaN,4000883,Taxi,NaN,NaN,NaN,NaN
14,10/16/2018,0:21,NaN,NaN,40.759018,-73.855156,"(40.759018, -73.855156)",GRAND CENTRAL PKWY,NaN,NaN,...,Other Vehicular,NaN,NaN,NaN,4001129,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
15,10/16/2018,0:27,MANHATTAN,10033,40.847355,-73.935180,"(40.847355, -73.93518)",SAINT NICHOLAS AVENUE,WEST 178 STREET,NaN,...,NaN,NaN,NaN,NaN,4001626,Sedan,NaN,NaN,NaN,NaN
16,10/16/2018,0:40,MANHATTAN,10001,40.745617,-73.990820,"(40.745617, -73.99082)",NaN,NaN,800 AVENUE OF THE AMERICAS,...,Driver Inattention/Distraction,NaN,NaN,NaN,4001804,Garbage or Refuse,Sedan,NaN,NaN,NaN
17,10/16/2018,10:00,BRONX,10460,40.837994,-73.869150,"(40.837994, -73.86915)",COMMONWLTH AVENUE,MANSION STREET,NaN,...,Unspecified,NaN,NaN,NaN,4001121,Station Wagon/Sport Utility Vehicle,Pick-up Truck,NaN,NaN,NaN
18,10/16/2018,10:00,BROOKLYN,11205,40.696735,-73.972565,"(40.696735, -73.972565)",NaN,NaN,39 ADELPHI STREET,...,Unspecified,NaN,NaN,NaN,4001095,Sedan,Pick-up Truck,NaN,NaN,NaN
19,10/16/2018,10:00,BROOKLYN,11235,40.578266,-73.957820,"(40.578266, -73.95782)",BRIGHTON BEACH AVENUE,BRIGHTON 12 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4002676,Sedan,Taxi,NaN,NaN,NaN
20,10/16/2018,10:00,MANHATTAN,10022,40.762177,-73.966130,"(40.762177, -73.96613)",EAST 60 STREET,3 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4001657,Station Wagon/Sport Utility Vehicle,Taxi,NaN,NaN,NaN
21,10/16/2018,10:00,QUEENS,11368,40.735657,-73.859960,"(40.735657, -73.85996)",NaN,NaN,98-25 HORACE HARDING EXPRESSWAY,...,Unspecified,NaN,NaN,NaN,4001022,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
22,10/16/2018,10:00,QUEENS,11373,40.736840,-73.872600,"(40.73684, -73.8726)",NaN,NaN,90-40 55 AVENUE,...,NaN,NaN,NaN,NaN,4001128,Pick-up Truck,NaN,NaN,NaN,NaN
23,10/16/2018,10:00,NaN,NaN,40.614270,-74.156654,"(40.61427, -74.156654)",STATEN ISLAND EXPRESSWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4001723,Tractor Truck Diesel,Sedan,NaN,NaN,NaN
24,10/16/2018,10:00,NaN,NaN,40.636547,-73.925840,"(40.636547, -73.92584)",KINGS HIGHWAY,EAST 53 STREET,NaN,...,NaN,NaN,NaN,NaN,4002396,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
25,10/16/2018,10:05,NaN,NaN,40.866820,-73.839230,"(40.86682, -73.83923)",EAST GUN HILL ROAD,KINGSLAND AVENUE,NaN,...,Other Vehicular,NaN,NaN,NaN,4001680,Box Truck,Sedan,NaN,NaN,NaN
26,10/16/2018,10:08,BROOKLYN,11208,40.684002,-73.880870,"(40.684002, -73.88087)",NaN,NaN,55 HALE AVENUE,...,Unspecified,NaN,NaN,NaN,4002076,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
27,10/16/2018,10:10,NaN,NaN,NaN,NaN,NaN,CROSS BAY BOULEVARD,DESARC ROAD,NaN,...,Unspecified,NaN,NaN,NaN,4001325,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
28,10/16/2018,10:10,NaN,NaN,NaN,NaN,NaN,TRIBOROUGH BRIDGE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4002642,Tractor Truck Diesel,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
29,10/16/2018,10:15,BROOKLYN,11234,40.617496,-73.943380,"(40.617496, -73.94338)",NaN,NaN,3131 KINGS HIGHWAY,...,Unspecified,NaN,NaN,NaN,4001906,Sedan,Sedan,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409837,01/01/2017,7:30,NaN,NaN,NaN,NaN,NaN,ATLANTIC AVENUE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3592255,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
409838,01/01/2017,7:35,MANHATTAN,10001,40.754622,-73.997127,"(40.7546224, -73.9971269)",WEST 35 STREET,DYER AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,3591349,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
409839,01/01/2017,7:39,BROOKLYN,11207,40.669563,-73.883190,"(40.669563, -73.88319)",CLEVELAND STREET,BLAKE AVENUE,NaN,...,Unspecified,Unspecified,NaN,NaN,3590578,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE
409840,01/01/2017,8:00,BROOKLYN,11201,40.695993,-73.983213,"(40.6959932, -73.983213)",TILLARY STREET,GOLD STREET,NaN,...,Unspecified,NaN,NaN,NaN,3596302,NaN,NaN,NaN,NaN,NaN
409841,01/01/2017,8:00,STATEN ISLAND,10301,40.635902,-74.088792,"(40.6359017, -74.088792)",NaN,NaN,11 KINGSLEY PLACE,...,Unspecified,NaN,NaN,NaN,3590371,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
409842,01/01/2017,8:00,NaN,NaN,NaN,NaN,NaN,110 AVENUE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3590185,TAXI,PASSENGER VEHICLE,NaN,NaN,NaN
409843,01/01/2017,8:00,NaN,NaN,NaN,NaN,NaN,SHORE PARKWAY,25 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,3599045,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
409844,01/01/2017,8:00,NaN,NaN,40.666237,-73.760988,"(40.6662366, -73.7609885)",NaN,NaN,NaN,...,Other Vehicular,NaN,NaN,NaN,3590062,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
409845,01/01/2017,8:00,BROOKLYN,11210,40.636627,-73.942251,"(40.6366269, -73.9422507)",BROOKLYN AVENUE,FARRAGUT ROAD,NaN,...,Unspecified,NaN,NaN,NaN,3593027,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
409846,01/01/2017,8:00,QUEENS,11427,40.726229,-73.756703,"(40.726229, -73.7567029)",CLEARVIEW EXPRESSWAY,GRAND CENTRAL PARKWAY,NaN,...,NaN,NaN,NaN,NaN,3590137,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
409847,01/01/2017,8:20,BROOKLYN,11210,40.636828,-73.939166,"(40.6368284, -73.9391663)",NaN,NaN,3917 FARRAGUT ROAD,...,Unspecified,Unspecified,Unspecified,Unspecified,3590044,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON
409848,01/01/2017,8:30,NaN,NaN,NaN,NaN,NaN,EMPIRE BOULEVARD,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3590164,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
409849,01/01/2017,8:30,NaN,NaN,NaN,NaN,NaN,MORRIS AVENUE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,3590935,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
409850,01/01/2017,8:32,NaN,NaN,NaN,NaN,NaN,8 AVENUE,NaN,NaN,...,NaN,NaN,NaN,NaN,3590748,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
409851,01/01/2017,8:35,BROOKLYN,11213,40.672175,-73.933572,"(40.6721754, -73.9335716)",NaN,NaN,195 SCHENECTADY AVENUE,...,Unspecified,Unspecified,NaN,NaN,3595645,TAXI,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN
409852,01/01/2017,8:35,QUEENS,11691,40.594236,-73.772005,"(40.594236, -73.7720045)",BEACH 40 STREET,ROCKAWAY BEACH BOULEVARD,NaN,...,Unspecified,NaN,NaN,NaN,3590937,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
409853,01/01/2017,8:40,QUEENS,11429,40.711983,-73.738770,"(40.7119827, -73.7387698)",NaN,NaN,218-21 105 AVENUE,...,Unspecified,NaN,NaN,NaN,3590177,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
409854,01/01/2017,8:45,MANHATTAN,10036,40.762025,-74.001152,"(40.762025, -74.0011515)",12 AVENUE,WEST 42 STREET,NaN,...,Unspecified,NaN,NaN,NaN,3590599,TAXI,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN
409855,01/01/2017,9:00,BRONX,10459,40.827175,-73.888871,"(40.8271753, -73.8888715)",NaN,NaN,1130 BRYANT AVENUE,...,Unspecified,Unspecified,Unspecified,Unspecified,3590645,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON
409856,01/01/2017,9:00,QUEENS,11378,NaN,NaN,NaN,NaN,NaN,58-35 60 LANE,...,NaN,NaN,NaN,NaN,3590439,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN
409857,01/01/2017,9:00,QUEENS,11378,40.717997,-73.906831,"(40.7179972, -73.906831)",NaN,NaN,59-36 59 ROAD,...,Unspecified,NaN,NaN,NaN,3590445,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN
409858,01/01/2017,9:00,NaN,NaN,40.844608,-73.903471,"(40.8446076, -73.9034715)",NaN,NaN,NaN,...,Unspecified,Unspecified,NaN,NaN,3590730,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN
409859,01/01/2017,9:08,QUEENS,11373,40.735013,-73.866238,"(40.7350131, -73.8662385)",NaN,NaN,94-31 59 AVENUE,...,NaN,NaN,NaN,NaN,3590331,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
409860,01/01/2017,9:09,BRONX,10454,40.809698,-73.915633,"(40.8096976, -73.9156325)",EAST 142 STREET,SAINT ANNS AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,3590820,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN
409861,01/01/2017,9:15,MANHATTAN,10016,40.749725,-73.983622,"(40.7497247, -73.9836217)",EAST 36 STREET,5 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,3590910,TAXI,NaN,NaN,NaN,NaN
409862,01/01/2017,9:15,NaN,NaN,NaN,NaN,NaN,WEST 143 STREET,NaN,NaN,...,NaN,NaN,NaN,NaN,3590724,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
409863,01/01/2017,9:30,BROOKLYN,11210,40.636208,-73.948990,"(40.636208, -73.94899)",EAST 29 STREET,FARRAGUT ROAD,NaN,...,Unspecified,NaN,NaN,NaN,3604765,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
409864,01/01/2017,9:30,QUEENS,11004,40.748311,-73.709535,"(40.7483111, -73.7095345)",UNION TURNPIKE,263 STREET,NaN,...,Unspecified,NaN,NaN,NaN,3590063,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
409865,01/01/2017,9:44,BROOKLYN,11203,40.647007,-73.946260,"(40.6470069, -73.9462597)",TILDEN AVENUE,NEW YORK AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,3594310,NaN,NaN,NaN,NaN,NaN
409866,01/01/2017,9:45,NaN,NaN,NaN,NaN,NaN,SHORE PARKWAY,KNAPP STREET,NaN,...,NaN,NaN,NaN,NaN,3591176,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN,NaN

In [6]:
dfd = df["DATE"].value_counts()

In [7]:
dfd

12/15/2017    994
05/19/2017    964
05/18/2017    905
01/07/2017    895
12/14/2017    880
03/02/2018    874
04/28/2017    854
06/29/2018    843
06/22/2017    840
03/16/2017    834
06/14/2018    822
06/13/2017    822
10/30/2017    820
09/06/2018    819
09/15/2017    818
10/20/2017    816
05/12/2017    814
06/21/2018    811
11/17/2017    807
06/20/2017    807
06/19/2017    806
06/19/2018    805
11/16/2017    803
06/18/2018    803
05/11/2018    803
05/29/2018    801
06/12/2017    800
10/12/2018    799
05/25/2018    796
03/13/2017    790
             ...
11/23/2017    465
03/11/2018    463
07/29/2018    461
12/31/2017    458
02/26/2017    457
03/04/2018    456
11/25/2017    455
03/26/2017    454
01/04/2018    451
01/02/2017    447
12/03/2017    446
02/25/2018    446
01/01/2018    443
02/19/2017    436
02/19/2018    433
02/12/2017    432
02/20/2017    426
02/05/2017    425
01/29/2017    424
07/04/2017    422
01/21/2018    417
01/22/2017    408
05/28/2018    408
01/08/2017    406
01/28/2018    405
07/04/2018    404
04/01/2018    395
03/14/2017    374
05/29/2017    370
12/25/2017    329
Name: DATE, Length: 654, dtype: int64